import {barLabel,hatchSegments,wrapLabel} from './bar-layout';
import {type Spec,palette} from './model';
import {timelineDomain} from './resize';
export type Primitive={kind:'text';x:number;y:number;text:string;size:number;color:string;w?:number;align?:'center'|'left'}|{kind:'rect';x:number;y:number;w:number;h:number;color:string}|{kind:'line';x:number;y:number;x2:number;y2:number;color:string;strokeWidth?:number};
export type ExportPage=Primitive[];
const labels:Record<string,string>={title:'Study title',design:'Design',indexEvent:'Index event',exposure:'Exposure',comparator:'Comparator',entryPeriod:'Calendar entry period',episodeRule:'Episode selection',outcome:'Outcome',endRules:'* Follow-up stopping rules',footnotes:'Figure footnotes',abbreviations:'Abbreviations'};
function lines(text:string,limit=95):string[]{return text.split('\n').flatMap(t=>{const chunks=t.match(new RegExp(`.{1,${limit}}(?:\\s|$)|.{1,${limit}}`,'g'));return chunks?.map(s=>s.trim())??[''];});}
export function exportPages(spec:Spec):ExportPage[]{const pages:ExportPage[]=[];const t=(p:ExportPage,x:number,y:number,text:string,size=17,color='#142842')=>p.push({kind:'text',x,y,text,size,color});const header=(title:string)=>{const p:ExportPage=[];lines(title,65).slice(0,2).forEach((line,i)=>t(p,30,24+i*28,line,24));t(p,30,82,'Study Design Diagram Studio · by Black Swan Causal Labs',14,'#527080');t(p,30,668,'© '+new Date().getFullYear()+' Black Swan Causal Labs · blackswancausallabs.com',13,'#527080');return p;};
const {min,max}=timelineDomain(spec);const x=(d:number)=>300+(d-min)/(max-min)*650;
const batches:{element:Spec['elements'][number];height:number}[][]=[[]];let used=0;for(const element of spec.elements){const layout=barLabel(element,Math.max(8,x(element.end??0)-x(element.start??0)));const height=layout.inside?50:Math.max(44,(layout.lines.length+layout.dateLines.length)*16+12);if(used+height>414&&batches[batches.length-1].length){batches.push([]);used=0;}batches[batches.length-1].push({element,height});used+=height;}for(const batch of batches){const p=header(spec.details.title);const annotation=wrapLabel('Day 0 — '+(spec.details.indexEvent||'Index event not specified'),100);annotation.slice(0,2).forEach((line,i)=>t(p,30,108+i*18,line+(i===1&&annotation.length>2?' … (see definitions)':''),14));const ticks=[...new Set([min,Math.round(min/2),0,Math.round(max/2),max])].sort((a,b)=>a-b);for(const d of ticks){p.push({kind:'line',x:x(d),y:178,x2:x(d),y2:600,color:d===0?'#142842':'#dce4eb',strokeWidth:d===0?4:0.7});t(p,x(d)-12,153,String(d),15);}let rowY=180;batch.forEach(({element:e,height})=>{const centerY=rowY+height/2;const y=centerY-17;rowY+=height;const known=e.start!==null&&e.end!==null;const a=x(e.start??0),b=x(e.end??0);const w=Math.max(8,b-a),bx=e.start===e.end?a-4:a;const label=barLabel(e,w);const labelY=centerY-(label.lines.length+label.dateLines.length)*8;if(!label.inside){label.lines.forEach((line,j)=>t(p,30,labelY+j*16,line,14));label.dateLines.forEach((line,j)=>t(p,30,labelY+(label.lines.length+j)*16,line,12,'#62758a'));}if(known){const follow=e.category==='follow-up';p.push({kind:'rect',x:bx,y,w,h:34,color:follow?'#effafa':palette[e.category]});if(follow)for(const line of hatchSegments(bx,y,w,34))p.push({kind:'line',...line,color:palette[e.category]});if(label.inside){if(follow){const mask=Math.max(e.label.length*8.5,label.dates.length*7.2)+12;p.push({kind:'rect',x:bx+(w-mask)/2,y:y+3,w:mask,h:34,color:'#effafa'});}p.push({kind:'text',x:bx+8,y:y+3,text:e.label,size:14,color:follow?'#142842':'#ffffff',w:w-16,align:'center'},{kind:'text',x:bx+8,y:y+21,text:label.dates,size:12,color:follow?'#142842':'#ffffff',w:w-16,align:'center'});}}else t(p,550,y,'Unresolved',16,'#986317');});if(!batch.length)t(p,30,200,'Blank canvas — no assessment windows specified.',20);t(p,30,629,'Days relative to day zero · Inclusive boundaries · Short-window widths not to scale',14);pages.push(p);}
let p=header('Study definitions and sources');let y=120;const add=(heading:string,value:string)=>{const block=lines(`${heading}: ${value||'Not specified'}`,90);if(y+block.length*23>615&&block.length*23<495){pages.push(p);p=header('Study definitions and sources (continued)');y=120;}for(const line of block){if(y>615){pages.push(p);p=header('Study definitions and sources (continued)');y=120;}t(p,30,y,line,17);y+=23;}y+=14;};for(const [k,label] of Object.entries(labels))add(label,spec.details[k as keyof Spec['details']]);for(const e of spec.elements){add(e.label,e.rule);add('Source / note',e.source);}pages.push(p);return pages;}
export async function makePowerPoint(spec:Spec){const {default:PptxGenJS}=await import('pptxgenjs');const pptx=new PptxGenJS();pptx.defineLayout({name:'STUDY',width:13.333333,height:9.333333});pptx.layout='STUDY';pptx.author='Black Swan Causal Labs';pptx.subject='Study design schematic';pptx.title=spec.details.title;pptx.company='Black Swan Causal Labs';for(const page of exportPages(spec)){const slide=pptx.addSlide();slide.background={color:'FFFFFF'};for(const e of page){const color=e.color.slice(1);if(e.kind==='text')slide.addText(e.text,{x:e.x/75,y:e.y/75,w:(e.w??(970-e.x))/75,h:0.36,fontSize:e.size*0.96,fontFace:'Arial',color,margin:0,breakLine:false,valign:'top',align:e.align??'left'});else if(e.kind==='rect')slide.addShape(pptx.ShapeType.rect,{x:e.x/75,y:e.y/75,w:e.w/75,h:e.h/75,line:{color,transparency:100},fill:{color}});else slide.addShape(pptx.ShapeType.line,{x:e.x/75,y:e.y/75,w:(e.x2-e.x)/75,h:(e.y2-e.y)/75,line:{color,width:e.strokeWidth??0.7}});}slide.addNotes('Generated from the current study specification. Review source definitions and missing information before use.');}return pptx;}
export async function makePdf(spec:Spec,fontBase64:string){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:'landscape',unit:'pt',format:[1000,700]});pdf.addFileToVFS('DejaVuSans.ttf',fontBase64);pdf.addFont('DejaVuSans.ttf','DejaVu','normal');pdf.setFont('DejaVu');exportPages(spec).forEach((page,i)=>{if(i)pdf.addPage([1000,700],'landscape');for(const e of page){if(e.kind==='text'){pdf.setTextColor(e.color);pdf.setFontSize(e.size);pdf.text(e.text,e.x+(e.align==='center'?(e.w??0)/2:0),e.y+e.size,{align:e.align??'left'});}else if(e.kind==='rect'){pdf.setFillColor(e.color);pdf.rect(e.x,e.y,e.w,e.h,'F');}else{pdf.setDrawColor(e.color);pdf.setLineWidth(e.strokeWidth??0.7);pdf.line(e.x,e.y,e.x2,e.y2);}}});return pdf;}
export async function exportDocument(spec:Spec,format:'pdf'|'pptx',filename:string){if(format==='pptx'){await (await makePowerPoint(spec)).writeFile({fileName:filename+'.pptx'});return;}const response=await fetch('/DejaVuSans.ttf');if(!response.ok)throw Error('Unable to load the PDF font. Please retry.');const bytes=new Uint8Array(await response.arrayBuffer());let data='';for(let i=0;i<bytes.length;i+=8192)data+=String.fromCharCode(...bytes.subarray(i,i+8192));(await makePdf(spec,btoa(data))).save(filename+'.pdf');}
