import { specSchema, elementSchema, detailsSchema, type Spec, updateElement, addElement, updateDetails, issues, blankSpec, removeElement, reorderElements, reviewChecklist } from './model';
import { renderSvg } from './svg';
import { z } from 'zod';
type Snapshot={spec:Spec;revision:number};
type Tool={name:string;description:string;inputSchema:Record<string,unknown>;execute:(input:unknown)=>Promise<unknown>};
type Context={registerTool:(tool:Tool,options?:{signal:AbortSignal})=>unknown;unregisterTool?:(name:string)=>void};
const str={type:'string'};const num={type:['integer','null'],minimum:-36500,maximum:36500};
const elementProperties={id:str,label:{type:'string',maxLength:100},category:{enum:['washout','eligibility','exclusion','covariates','follow-up'],type:'string'},start:num,end:num,rule:str,source:str,endpointLabel:{type:'string',maxLength:80}};
const detailProperties=Object.fromEntries(Object.keys(detailsSchema.shape).map(k=>[k,str]));
const object=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
const revision=z.number().int().nonnegative();
export function createTools(read:()=>Snapshot,commit:(s:Spec,expected:number,label:string)=>void):Tool[]{
const tool=(name:string,description:string,inputSchema:Record<string,unknown>,run:(input:unknown)=>unknown):Tool=>({name,description,inputSchema,execute:async input=>{try{return {content:[{type:'text',text:JSON.stringify(run(input))}]};}catch(e){return {isError:true,content:[{type:'text',text:e instanceof Error?e.message:'Invalid request'}]};}}});
return [
tool('get_study_spec','Read the current specification and revision before editing. Blank strings and null days mean unresolved; never infer missing study facts.',object({}),()=>read()),
tool('update_design_element','Update only supplied fields on one timeline element. Use the current revision. Record source evidence or mark researcher-defined changes.',object({id:str,expected_revision:{type:'integer'},patch:object(Object.fromEntries(Object.entries(elementProperties).filter(([k])=>k!=='id')))},['id','expected_revision','patch']),input=>{const p=z.object({id:z.string(),expected_revision:revision,patch:elementSchema.omit({id:true}).partial()}).strict().parse(input);commit(updateElement(read().spec,p.id,p.patch),p.expected_revision,'Agent updated a window');return read();}),
tool('add_design_element','Add a new window with a unique ID. Use null for unknown timing and explicit evidence in source.',object({expected_revision:{type:'integer'},element:object(elementProperties,Object.keys(elementProperties).filter(k=>k!=='endpointLabel'))},['expected_revision','element']),input=>{const p=z.object({expected_revision:revision,element:elementSchema}).strict().parse(input);commit(addElement(read().spec,p.element),p.expected_revision,'Agent added a window');return read();}),
tool('remove_design_element','Remove one window by ID. Read the current specification first. All other windows and study details are preserved. Reversible using the dashboard Undo button.',object({id:str,expected_revision:{type:'integer'}},['id','expected_revision']),input=>{const p=z.object({id:z.string(),expected_revision:revision}).strict().parse(input);commit(removeElement(read().spec,p.id),p.expected_revision,'Agent removed a window');return read();}),
tool('reorder_design_elements','Reorder rows top to bottom. Supply every current window ID exactly once in ordered_ids. Does not change dates, labels, definitions or study details. Reversible using the dashboard Undo button.',object({ordered_ids:{type:'array',items:str,maxItems:60,uniqueItems:true},expected_revision:{type:'integer'}},['ordered_ids','expected_revision']),input=>{const p=z.object({ordered_ids:z.array(z.string()).max(60),expected_revision:revision}).strict().parse(input);commit(reorderElements(read().spec,p.ordered_ids),p.expected_revision,'Agent reordered windows');return read();}),
tool('update_study_details','Update study title, index event, groups, outcome, calendar entry, episode rules, stopping rules, footnotes or abbreviations. Does not change window dates.',object({expected_revision:{type:'integer'},patch:object(detailProperties)},['expected_revision','patch']),input=>{const p=z.object({expected_revision:revision,patch:detailsSchema.partial()}).strict().parse(input);commit(updateDetails(read().spec,p.patch),p.expected_revision,'Agent updated study details');return read();}),
tool('import_study_spec','Replace the entire current design from a structured specification. Read the current revision first. Reversible using Undo.',object({expected_revision:{type:'integer'},spec:object({schemaVersion:{const:1,type:'integer'},details:object(detailProperties,Object.keys(detailProperties).filter(k=>!['footnotes','abbreviations'].includes(k))),elements:{type:'array',items:object(elementProperties,Object.keys(elementProperties).filter(k=>k!=='endpointLabel'))}},['schemaVersion','details','elements'])},['expected_revision','spec']),input=>{const p=z.object({expected_revision:revision,spec:specSchema}).strict().parse(input);commit(p.spec,p.expected_revision,'Agent imported a study');return read();}),
tool('clear_study_spec','Clear all study details and windows to start a blank canvas. Reversible using Undo.',object({expected_revision:{type:'integer'}},['expected_revision']),input=>{const p=z.object({expected_revision:revision}).strict().parse(input);commit(blankSpec(),p.expected_revision,'Canvas cleared');return read();}),
tool('validate_study_spec','Return the same structured completeness checklist shown on the dashboard, with stable IDs, labels, complete flags, missing window names and completion totals, plus review items. Read-only; populated information does not establish causal validity or source accuracy.',object({}),()=>{const {spec,revision}=read();const checklist=reviewChecklist(spec);return {revision,reviewItems:issues(spec),checklist,summary:{complete:checklist.filter(c=>c.complete).length,total:checklist.length},scope:'Information presence only; not source verification or study validity.'};}),
tool('export_schematic','Return an SVG document containing the current schematic, definitions and sources. Does not trigger a browser download.',object({}),()=>({revision:read().revision,mimeType:'image/svg+xml',svg:renderSvg(read().spec,'',true)}))
];}
export async function registerTools(tools:Tool[],signal:AbortSignal){const doc=document as Document&{modelContext?:Context};const nav=navigator as Navigator&{modelContext?:Context};const ctx=doc.modelContext??nav.modelContext;if(!ctx)return {available:false,cleanup:()=>{}};const names:string[]=[];const cleanup=()=>{for(const n of names){try{ctx.unregisterTool?.(n);}catch{}}};try{for(const t of tools){if(signal.aborted)break;await ctx.registerTool(t,{signal});names.push(t.name);}return {available:!signal.aborted,cleanup};}catch(e){cleanup();throw e;}}
