'use client';
import { Checkbox } from '@/components/ui/checkbox';
import { useState, useRef, useEffect, useCallback } from 'react';
import { Download, Upload, Undo2, Plus, Trash2, Layers3, FileCheck2, PencilLine, Check } from 'lucide-react';
import Information from './information';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { seed, type Spec, type Element, specSchema, categories, categoryLabels, palette, updateElement, addElement, updateDetails, issues, reviewChecklist, blankSpec } from '@/lib/study/model';
import { renderSvg } from '@/lib/study/svg';
import Timeline from './timeline';
import { createTools, registerTools } from '@/lib/study/webmcp';
function download(content:string,type:string,name:string){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function WindowForm({element,revision,onSave,onDelete}:{element:Element;revision:number;onSave:(e:Element,r:number)=>void;onDelete:(r:number)=>void}){const [draft,setDraft]=useState(element);const [base]=useState(revision);const set=(k:keyof Element,v:unknown)=>setDraft(d=>({...d,[k]:v}));return <form onSubmit={e=>{e.preventDefault();onSave(draft,base)}} className="window-form"><div className="inspector-heading"><PencilLine size={18}/><h2>Edit window</h2></div><Field label="Name"><input maxLength={100} required value={draft.label} onChange={e=>set('label',e.target.value)}/></Field><Field label="Category"><Select value={draft.category} onValueChange={v=>set('category',v)}><SelectTrigger className="category-select"><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{categoryLabels[c]}</SelectItem>)}</SelectContent></Select></Field><div className="two-fields">{(['start','end'] as const).map(k=><Field key={k} label={k==='start'?'Start day':'End day'}><input type="number" min={-36500} max={36500} step={1} placeholder="Unknown" value={draft[k]??''} onChange={e=>set(k,e.target.value===''?null:Number(e.target.value))}/></Field>)}</div><p className="hint">Relative to day zero, inclusive. Leave blank if unknown.</p>{draft.category==='follow-up'&&<Field label="Endpoint label (optional)"><input maxLength={80} value={draft.endpointLabel} placeholder="e.g. End of follow-up*" onChange={e=>set('endpointLabel',e.target.value)}/><small>Keep the end day as the maximum; define the actual stopping events below.</small></Field>}<Field label="Assessment rule"><textarea rows={4} value={draft.rule} onChange={e=>set('rule',e.target.value)} /></Field><Field label="Source / researcher note"><textarea rows={3} value={draft.source} onChange={e=>set('source',e.target.value)}/></Field><Button type="submit" className="apply">Apply changes</Button><Button type="button" variant="ghost" className="remove" onClick={()=>onDelete(base)}><Trash2/>Remove window</Button></form>}
const detailLabels:Record<keyof Spec['details'],string>={title:'Study title',design:'Design / description',indexEvent:'Index event (day zero)',exposure:'Exposure definition',comparator:'Comparator definition',entryPeriod:'Calendar entry period',episodeRule:'Episode selection',outcome:'Outcome',endRules:'Follow-up stopping rules',footnotes:'Figure footnotes (optional)',abbreviations:'Abbreviation key (optional)'};
function Details({spec,revision,onSave}:{spec:Spec;revision:number;onSave:(d:Spec['details'],r:number)=>void}){const [d,setD]=useState(spec.details);const [base]=useState(revision);return <form onSubmit={e=>{e.preventDefault();onSave(d,base)}} className="details-form"><div className="section-heading"><h2>Study details</h2><Button variant="outline" type="submit"><Check/>Apply study details</Button></div><div className="details-grid">{(Object.keys(detailLabels) as (keyof typeof detailLabels)[]).map(k=><Field key={k} label={detailLabels[k]}>{['endRules','episodeRule','footnotes','abbreviations'].includes(k)?<textarea rows={3} value={d[k]} placeholder="Not specified in the reference" onChange={e=>setD({...d,[k]:e.target.value})}/>:<input value={d[k]} required={k==='title'} maxLength={k==='title'?180:6000} placeholder="Not specified in the reference" onChange={e=>setD({...d,[k]:e.target.value})}/>}</Field>)}</div></form>}
export default function Editor(){const [state,setState]=useState({spec:seed,revision:0});const current=useRef(state);const history=useRef<Spec[]>([]);const [selected,setSelected]=useState('washout');const [message,setMessage]=useState('Reference loaded. Save JSON to keep your work before leaving.');const [error,setError]=useState('');const [exporting,setExporting]=useState(false);const [connection,setConnection]=useState('Checking browser support…');const file=useRef<HTMLInputElement>(null);
const commit=useCallback((spec:Spec,expected:number,label:string)=>{if(expected!==current.current.revision)throw Error('The design changed while you were editing. Select the window again or reload its fields before applying.');const valid=specSchema.parse(spec);history.current.push(current.current.spec);const next={spec:valid,revision:current.current.revision+1};current.current=next;setState(next);setMessage(label+' · Save JSON to keep this revision.');setError('');},[]);
const safe=(f:()=>void)=>{try{f();}catch(e){setError(e instanceof Error?e.message:'Unable to apply change.')}};
useEffect(()=>{const ctrl=new AbortController();let dispose=()=>{};const availableTools=createTools(()=>current.current,commit);registerTools(availableTools,ctrl.signal).then(r=>{dispose=r.cleanup;if(ctrl.signal.aborted)dispose();else setConnection(r.available?`WebMCP available · ${availableTools.length} tools`:'Manual editing · WebMCP unavailable in this browser');}).catch(()=>{if(!ctrl.signal.aborted)setConnection('Manual editing · WebMCP registration failed');});return()=>{ctrl.abort();dispose();};},[commit]);
useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(current.current.revision>0){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
const {spec,revision}=state;const active=spec.elements.find(e=>e.id===selected);const checks=reviewChecklist(spec);const timingWarnings=issues(spec).filter(item=>item.includes('extends after day zero'));
const detailsStarted=Object.entries(spec.details).some(([key,value])=>value.trim()&&(key!=='title'||value!=='Untitled study'));
const focusSection=(section:string,selector:string)=>{requestAnimationFrame(()=>{const panel=document.getElementById(section);panel?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});panel?.querySelector<HTMLElement>(selector)?.focus({preventScroll:true});});};
const addWindow=()=>safe(()=>{const id='window-'+crypto.randomUUID();const e:Element={id,label:'New assessment window',category:'eligibility',start:null,end:null,rule:'',source:'',endpointLabel:''};commit(addElement(current.current.spec,e),current.current.revision,'Window added');setSelected(id);focusSection('window-inspector','input');});

return <div className="studio"><header className="topbar"><a href="/" className="brand"><Layers3 size={24}/><span>Study Design Diagram Studio<small>by Black Swan Causal Labs</small></span></a><div className="actions"><input type="file" accept=".json,application/json" hidden ref={file} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const base=current.current.revision;try{if(f.size>1000000)throw Error('Choose a JSON file smaller than 1 MB.');const next=specSchema.parse(JSON.parse(await f.text()));commit(next,base,'Study imported');setSelected(next.elements[0]?.id??'');}catch(err){setError(err instanceof Error?err.message:'Invalid study JSON');}e.target.value='';}}/><Button variant="outline" onClick={()=>file.current?.click()}><Upload/>Import JSON</Button><Button variant="outline" onClick={()=>{download(JSON.stringify(spec,null,2),'application/json','study-specification.json');setMessage('JSON downloaded. Keep this file to restore your design.');}}><Download/>Save JSON</Button><DropdownMenu><DropdownMenuTrigger asChild><Button disabled={exporting}><Download/>{exporting?'Exporting…':'Export'}</Button></DropdownMenuTrigger><DropdownMenuContent align="end">{(['svg','pdf','pptx'] as const).map(format=><DropdownMenuItem key={format} onSelect={()=>{void (async()=>{setExporting(true);setError('');try{const name=`study-schematic-r${revision}-${Date.now()}`;if(format==='svg')download(renderSvg(current.current.spec,'',true),'image/svg+xml',name+'.svg');else{const {exportDocument}=await import('@/lib/study/export');await exportDocument(current.current.spec,format,name);}setMessage(`${format.toUpperCase()} exported with the current applied changes.`);}catch(e){setError(e instanceof Error?e.message:'Export failed. Please retry.');}finally{setExporting(false);}})();}}>{format==='pptx'?'PowerPoint (.pptx)':format.toUpperCase()}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><span id="canvas-mcp-control"/></div></header>
<main><Tabs defaultValue="workspace"><TabsList variant="line" className="main-tabs"><TabsTrigger value="workspace">Workspace</TabsTrigger><TabsTrigger value="about">About</TabsTrigger><TabsTrigger value="faq">FAQ & limitations</TabsTrigger><TabsTrigger value="webmcp">WebMCP</TabsTrigger></TabsList><TabsContent value="workspace" forceMount className="workspace-tab"><div className="page-heading"><div><h1>{spec.details.title}</h1><p>{spec.details.design||'Study design'} <span className="separator">/</span> Revision {revision}</p></div><div className="canvas-actions"><Button variant="outline" onClick={()=>safe(()=>{commit(blankSpec(),revision,'Canvas cleared');setSelected('');})}><Trash2/>Clear canvas</Button><Button variant="outline" onClick={()=>safe(()=>{commit(seed,revision,'Example loaded');setSelected('washout');})}>Load example</Button><Button variant="outline" disabled={!history.current.length} onClick={()=>{const prev=history.current.pop();if(prev){const next={spec:prev,revision:revision+1};current.current=next;setState(next);setMessage('Last change undone.');setError('');}}}><Undo2/>Undo</Button></div></div>
<div className="workspace"><section className="canvas-panel"><div className="canvas-toolbar"><h2>Study design diagram schematic</h2><div className="legend">{categories.map(c=><span key={c}><i style={{background:palette[c]}}/>{categoryLabels[c]}</span>)}</div></div>{spec.elements.length?<Timeline spec={spec} revision={revision} selected={selected} onSelect={setSelected} onResize={(id,edge,value,r)=>safe(()=>commit(updateElement(current.current.spec,id,{[edge]:value}),r,'Window resized'))}/>:<Empty className="start-guide" id="start-guide"><EmptyHeader><EmptyTitle>Start your study schematic</EmptyTitle><EmptyDescription>Define your study, then add its assessment windows.</EmptyDescription></EmptyHeader><ol className="start-steps"><li><span className="step-number">1</span><div><h3>Fill out study details</h3><p>Name your study and define day zero, study groups and follow-up. Leave unknown information blank, then select “Apply study details.”</p><Button variant={detailsStarted?'outline':'default'} onClick={()=>focusSection('study-details','input')}>{detailsStarted?'Review study details':'Fill out study details'}</Button></div></li><li><span className="step-number">2</span><div><h3>Add your first window</h3><p>Add a washout, inclusion, exclusion, covariate or follow-up window. Enter its dates and rule, then apply changes.</p><Button id="first-window-button" variant={detailsStarted?'default':'outline'} onClick={addWindow}><Plus/>Add your first window</Button></div></li></ol><p className="hint">You can start with a window and return to the study details at any time.</p></Empty>}{spec.elements.length>0?<div className="canvas-footer"><span>{spec.elements.length} windows · Drag an edge to adjust dates</span><Button variant="outline" onClick={addWindow}><Plus/>Add window</Button></div>:null}<div className="followup-note"><strong>Follow-up ends at the first of:</strong><p>{spec.details.endRules||'Not specified — add the stopping rules below.'}</p></div>{(['footnotes','abbreviations'] as const).map(key=>spec.details[key].trim()&&<div className="followup-note" key={key}><strong>{key==='footnotes'?'Figure footnotes':'Abbreviations'}</strong><p>{spec.details[key]}</p></div>)}</section><aside className="inspector" id="window-inspector">{active?<WindowForm key={active.id+'-'+revision} element={active} revision={revision} onSave={(e,r)=>safe(()=>{const {id,...patch}=e;commit(updateElement(current.current.spec,id,patch),r,'Window updated');})} onDelete={r=>safe(()=>{commit({...spec,elements:spec.elements.filter(e=>e.id!==active.id)},r,'Window removed');setSelected(spec.elements.find(e=>e.id!==active.id)?.id??'');})}/>:<div className="empty"><h2>{spec.elements.length?"Select a window":"Your window editor"}</h2><p>{spec.elements.length?"Choose a row on the schematic to edit its dates, rule and source.":"After you add your first window, its dates, rule and source fields will appear here."}</p></div>}</aside></div>
<div className="feedback" role="status">{message}</div>{error?<div className="error" role="alert">{error}</div>:null}
<section className="details-panel" id="study-details"><Details key={revision} spec={spec} revision={revision} onSave={(d,r)=>safe(()=>{commit(updateDetails(current.current.spec,d),r,'Study details updated');if(!current.current.spec.elements.length){setMessage('Study details applied. Next, add your first assessment window.');focusSection('start-guide','#first-window-button');}})}/></section>
<section className="review-panel"><div><FileCheck2 size={22}/><h2>Review before use</h2><span aria-live="polite">{checks.filter(c=>c.complete).length} / {checks.length} complete</span></div><p>Checked automatically when you apply study details or window changes. Checks indicate information is present; verify definitions and sources before using the figure.</p><div className="review-checklist">{checks.map(check=><div className="review-check" key={check.id}><Checkbox id={'review-'+check.id} checked={check.complete} disabled aria-labelledby={'review-label-'+check.id}/><div><label id={'review-label-'+check.id} htmlFor={'review-'+check.id}>{check.label}</label>{check.missing.length>0&&<p>Missing: {check.missing.join('; ')}</p>}</div></div>)}</div>{timingWarnings.length>0&&<aside className="review-warnings"><h3>Timing to review</h3><ul>{timingWarnings.map(w=><li key={w}>{w}</li>)}</ul></aside>}<p>The preloaded example was transcribed from the supplied figure and has not been verified against its manuscript.</p></section>
</TabsContent><Information/></Tabs><footer><span>{connection}</span><span>Session-only workspace · Save JSON to preserve edits</span></footer></main><div className="brand-footer">© {new Date().getFullYear()} <a href="https://blackswancausallabs.com" target="_blank" rel="noreferrer">Black Swan Causal Labs</a>. <a href="/LICENSE" target="_blank" rel="noreferrer">Apache 2.0</a> · <a href="/THIRD_PARTY_NOTICES.txt" target="_blank" rel="noreferrer">Third-party notices</a></div></div>}
